# Generated by Django 5.1.3 on 2024-11-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_child_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='child',
            name='token',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('parent', 'name')},
        ),
    ]
