# Generated by Django 5.1.3 on 2024-11-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_child_image_user_image_alter_child_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
