# Generated by Django 5.1.3 on 2024-11-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_draw_created_at_draw_is_locked_alter_child_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='draw',
            unique_together={('name', 'child')},
        ),
    ]
