# Generated by Django 5.1.3 on 2024-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
