# Generated by Django 5.1.3 on 2025-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_draw_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
