services:
  app:
    build: 
      context: ./../../.
    ports: 
      - "8000:8000"
    volumes:
      - ../../app:/usr/src/app  # Syncs local app changes with the container
      - dev-static-app:/vol/web
    command: 
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db  
      - redis
      - celery_worker
      - celery_beat
  db:
    image: postgres:alpine
    volumes:
      - dev-db-app:/var/lib/postgresql/app
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
  

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: 
      context: ./../../.
    container_name: celery_worker
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ../../app:/usr/src/app 
    depends_on:
      - redis

  celery_beat:
    build:
      context: ./../../.
    container_name: celery_beat
    command: celery -A app beat --loglevel=info
    volumes:
      - ../../app:/usr/src/app  
    environment: 
      - DB_HOST=db             # Database hostname
      - DB_NAME=devdb          # Database name
      - DB_USER=devuser        # Database user
      - DB_PASS=changeme       # Database password
      - DEBUG=1  
    depends_on:
      - redis
      - db
 

volumes:
  dev-db-app:     
  dev-static-app:




