name: tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"
